### ISSUE TITLE
Hunter Traps throw a lua error

### ISSUE THREAD

**Issue by ahillgrove** [sidamakid/ASCT-World-Of-Warcraft#1]
It references Shared_Hunter_spells but that's not the name of the field.

In SARTE-Text/SARTE-Text-Shared-Spell-Cooldowns/SARTE-Text-Traps.lua, this change fixes it:
-      if self and unit == "player" and SpellTableHunterTraps[SDT_GetEnglishName(spellName)] and SARTESPELLDB["Shared_Hunter_spells"]["Traps"] == true then
+      if unit == "player" and SpellTableHunterTraps[SDT_GetEnglishName(spellName)] and SARTESPELLDB["Hunter_Traps"]["Traps"] == true then

**Comment by sidamakid** [comment]
Thank you for the information I will fix that in the next release. Really apparated.
