### ISSUE TITLE
Fix for tracking other players' abilities

### ISSUE THREAD

**Issue by ahillgrove** [sidamakid/ASCT-World-Of-Warcraft#2]
The and/or construction for checking spells you have is losing the restriction on unit == "player"
Change
`if unit == "player" and`
to
```
if unit == "player" then
  if
  -- checks for spells
  then
    -- add event
  end
end
```

**Comment by sidamakid** [comment]
Ok thank you for the information. I will make that change in my next update! I will release it today I have been trying to fix that for a long time. I really love it that you sent this issue.
