### ISSUE TITLE
error when skill level increase.. ex. dagger for priest.

### ISSUE THREAD

**Issue by MelchiorGaspar** [sidamakid/ASCT-World-Of-Warcraft#6]
This v8.9.9 I think.. and WoW-wrath-classic-v3.4.2

1x ..._Scrolling_Combat_Text/Gains_Losses/Skill_Gained.lua:18: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Advanced_Scrolling_Combat_Text/Gains_Losses/Skill_Gained.lua"]:18: in function <..._Scrolling_Combat_Text/Gains_Losses/Skill_Gained.lua:7>

Locals:
(*temporary) = "You have gained the %s skill."
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by sidamakid** [comment]
Fixing it as fast as I can.

**Comment by MelchiorGaspar** [comment]
ty for your effort.
