### ISSUE TITLE
Doesn't work in Season of Discovery:

### ISSUE THREAD

**Issue by Lexlutheran** [sidamakid/ASCT-World-Of-Warcraft#7]
I type /asct and nothing happens, the minimap icon isn't there, and it doesn't show up under the options menu despite showing the addon is installed under the addons menu itself. This is similarly the case when it's the only addon enabled.

**Comment by sidamakid** [comment]
Thank you For The Bug Report! I'll get work on it as soon as I can! Sorry it's been slow with updates. Been super busy with life.

**Comment by Lexlutheran** [comment]
No worries; appreciate the project and your time!

**Comment by sidamakid** [comment]
Right on!
