### ISSUE TITLE
Errors and does not load: TWW

### ISSUE THREAD

**Issue by kaleide** [sidamakid/ASCT-World-Of-Warcraft#8]
Message: ...d_Scrolling_Combat_Text/ASCT_API/Index/Get_Index.lua:13: attempt to call global 'GetSpellInfo' (a nil value)
Time: Thu Oct  3 16:54:31 2024
Count: 1
Stack: ...d_Scrolling_Combat_Text/ASCT_API/Index/Get_Index.lua:13: attempt to call global 'GetSpellInfo' (a nil value)
[string "@Interface/AddOns/Advanced_Scrolling_Combat_Text/ASCT_API/Index/Get_Index.lua"]:13: in function `GetSpellInfo'
[string "@Interface/AddOns/Advanced_Scrolling_Combat_Text/Modules/locale/Advanced_Scrolling_Combat_Text-Spells.lua"]:29: in function <...les/locale/Advanced_Scrolling_Combat_Text-Spells.lua:21>

Locals: spell = 18499
(*temporary) = nil
(*temporary) = 18499
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"

Saw the addon and was curious, but it would not load because of the errors. I attempted to remove a bunch just to see if it would load, but it just kept throwing another spellid.

**Comment by sidamakid** [comment]
Oh yeah I haven't updated the GitHub page for a while now. But it should work in War Within now.
